### PR TITLE
feat: auto start rough notation animation on slide change

### LINKED ISSUE #2: Add auto apply method for slides

### PR DESCRIPTION
**Pull request by mcanouil**
This PR adds an event listener to draw the rough notation on slide changes (see <https://revealjs.com/events/>).
(It keeps the key binding by naming the function and reusing it for both events, although with the auto start feature, the key binding is useless.)

Fixes #2

### CODE REVIEW

**Comment by EmilHvitfeldt** [comment]
I would use something like [slide states](https://github.com/WhitakerLab/slides/blob/master/reveal.js/README.md#slide-states) instead of `slidechanged`, this way the user can do something like this to selectively apply it to slides

```md

## No auto

## Yes auto {.rn-auto}

```

**Comment by mcanouil** [comment]
I see, this could also be a global yaml option with the implementation you suggest.

**Comment by mcanouil** [comment]
I am closing this PR 😉

**Comment by ChoCho66** [comment]
I want to ask a stupid question.
How to use this `slidechanged` function?
Or how to use this "auto start rough notation"?

**Pull request closed without merging**
